### ISSUE TITLE
Issueベース開発

### ISSUE THREAD

**Issue by tatsuya582** [tatsuya582/zennta#4]
■Webアプリの概要
ZennやQiitaのAPIを利用して記事一覧や検索を同時にできるサービスです
読んだ履歴や後で読む、お気に入りなどができます。

■1週間辺りの開発に向けられる時間
- 1週間あたり：30時間

（ストーリポイント1消費するのに2時間を目安として、1週間あたりどれだけストーリポイントを消化できるか確認してください）

■ProjectsのURL
https://github.com/users/tatsuya582/projects/2/views/1?sumFields=%5B139982378%5D&hideItemsCount=false

■MVPリリースまで
- [x] create next-app
- [x] vercelにデプロイ
- [x] トップページ
- [x] ユーザー登録機能
- [x] ログイン機能
- [x] 一覧表示機能（未ログインでも閲覧可能）
- [x] 検索機能（未ログインでも閲覧可能）
- [x] 後で読む機能
- [x] お気に入り機能
- [x] お気に入り記事に自分用のメモをつける機能
- [x] 閲覧履歴表示

■MVP後
- [x] 利用規約
- [x] プライバシーポリシー
- [x] お問い合わせ
- [x] ファビコン
- [x] 独自ドメイン
- [x] お気に入り記事をグループ化できる機能
- [x] 他人のお気に入り記事のグループを閲覧機能
- [x] ここまで読んだ機能

■MVPレビュー依頼予定日
予定日：2024年 11月 17日

**Comment by kashiwagi-rena** [comment]
提出いただきありがとうございます。
確認です。ZennやQiitaのAPIのドキュメント等は読まれましたか？実装の仕方等流れは掴まれていますか？

**Comment by tatsuya582** [comment]
Qiitaは公式が用意してくれているので読んだことと
一覧を表示してみたりなどですが、少し触っているので実装の流れは掴んでいると思います。
Zennの方はAPIが用意されてないので自分で調べてQiitaと同じぐらいにはできているのですが、
公式で用意されていないAPIを使うのはまずいでしょうか？

**Comment by Mariko222** [comment]
お疲れさまです。

> Zennの方はAPIが用意されてないので自分で調べてQiitaと同じぐらいにはできているのですが、
> 公式で用意されていないAPIを使うのはまずいでしょうか？

Zennの記事を取得する方法について、いくつか記事が見受けられますのでおそらく問題ないかとは思うのですが、公式ではないAPIの場合突然の仕様変更や使えなくなったりといったケースも想定されるので、そういった考慮は必要になるかと思います。
またキャッチアップ度合いにもよりますが、QiitaとZenn両方のAPIを使用される予定なのであれば、機能実装とは別にAPI導入用のカードを作成したほうが良いかなと感じました。

**Comment by tatsuya582** [comment]
API導入用のカード追加しました。
よろしくお願いします

**Comment by Mariko222** [comment]
ご対応ありがとうございます
概ね良いかと思います、LGTMです！
