### ISSUE TITLE
MVPリリース

### ISSUE THREAD

**Issue by tatsuya582** [tatsuya582/zennta#68]
## 各種情報
サービスの概要とMVPで検証する事柄：ZennやQiitaのAPIを利用して記事一覧や検索を同時にできるサービスです 読んだ履歴や後で読む、お気に入りなどができます。
サービス名：Zennta
サービスURL：https://zennta.vercel.app/

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] 機能名
- [x] 一覧表示機能
- [x] 検索機能
- [x] 後で読む、お気に入り機能
- [x] お気に入り記事に自分用のメモをつける機能
- [x] 閲覧履歴表示

## サービスイメージがわかるようなスクリーンショット等
![image](https://github.com/user-attachments/assets/85cf7bbd-fe3b-420f-a4d7-1bc8faa40186)

**Comment by beppumasaki** [comment]
下記機能について確認ができませんでした。
-  検索機能
キーワード検索なのか、何を持って正しい挙動なのかが判断できませんでした。
![c083a1b6b98cc2c0f1304f7c8afcb5f4](https://github.com/user-attachments/assets/9d0e6112-517e-4cd8-a369-031317851656)

ご確認の上、必要であれば修正等を行ってください。
もし実装できているのであれば、コメントに確認手順を詳しく記載してください。
上記いずれかのご対応の上、RUNTEQアプリから再提出してください。

**Comment by tatsuya582** [comment]
この検索はQiitaのAPIを使っているのですが、どうやら本文も検索しているみたいです。
なので仕様になります。
![image](https://github.com/user-attachments/assets/5e2e2271-9949-4a24-adce-a105e0ffe239)

**Comment by beppumasaki** [comment]
機能確認が取れました。LGTMです。
引き続き本リリースに向けて開発頑張ってください。

以下、LGTMを出した方々に共通してお伝えしている内容になります。
（Webアプリを就職活動で活用される方向けの内容になります）

===== 本リリースまでに以下の項目を実装してください =====
□ 独自ドメイン反映
    -> DNSやSSLの対応も必要になるのでアピールになり、URLを書類等に記載するときの見栄えも良くなります。
□ OGP（静的 or 動的）
    -> SNS等でシェアするときの見栄えが良くなります。Webアプリであればどんなアプリでも取り入れられるので対応しておきましょう。
□ RSpec（モデルテスト+システムテスト or モデルテスト+リクエストテスト）
    -> 開発における品質の意識や開発効率の意識の高さをアピールできます。Request Specをメインに最低限各機能に正常にアクセスできるか程度はテストで確認できるようにしておきましょう。
□ CI（GitHubActions）
    -> 実際に開発現場でも使われており、アプリ外で技術のアピールが出来るものです。RSpecと合わせて実装を行いましょう。
□ Rubocopを使ってのリファクタリング
    -> Lintチェックツールは開発現場で広く使われています。コードのLintを整えておくことはチームで開発することを意識するうえでとても大切になるので取り入れておきましょう。

他のプログラミング学習者のWebアプリと異なることをアピールするために、よりインパクトのある機能を複数盛り込むことが重要になってきます。
□ SNSログイン（Google or LINE）
    -> ほとんどのアプリに取り入れられてユーザー体験の向上や技術のアピールにつながるので取り入れましょう。
□ 検索機能のアップデート（オートコンプリート、マルチ検索等）   ※検索機能がある場合
    -> 特にオートコンプリートは検索体験の向上だけではなくJS系の技術も取り入れていることをアピール出来るので積極的に取り入れましょう。

ユーザー体験という面では以下の項目も大切です。
□ オートログイン
    -> ユーザー登録後に再度ログイン操作を行わせないことでユーザー体験を向上させられます。
□ 使い方説明がある
    -> 初めて訪れたユーザーに呈して使い方の説明があることで体験を向上させられます。
□ レスポンシブ対応
    -> いずれのデバイスでも綺麗にサービスが活用できることで体験が良くなります。
□ 利用規約・プライバシーポリシーを未ログイン状態でも確認できる
    -> 利用規約・プライバシーポリシーがあることで、ちゃんとしたサービスという印象を与えられます。
□ ローディングアニメーション（処理が重い箇所）
    -> 処理が重い箇所に何の対応も無いとユーザーが正しく操作できたのか困惑してしまいます。そうした際はローディングアニメーションを表示させることで体験が向上します。
